image: Ubuntu2004
branches:
  only:
    - main

# set clone depth
clone_depth: 1

build_script:
  - #chmod +x appveyor/firmware.sh && ./appveyor/firmware.sh
  - touch sllin-firmware.tar.xz

artifacts:
  - path: sllin-firmware.tar.xz
    name: files

deploy:
  - provider: GitHub
    release: latest-main
    description: 'Builds slLIN firmware from latest main sources'
    artifact: files
    draft: false
    prerelease: true
    force_update: true
    auth_token:
      secure: bKQ2RgyJSqBdrQV8TFJ/1oSxxUH2tEPbpiXiwDYI+Adf1rw3aqGBnUp6jtVmnsbbQuX5XvPIl23pXiWRuhxIm7PycgMKU0nHWg5DAt3ftGw71rLl5xv6mgLLoHU
    on:
      branch: main                # release from main branch only

  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'slLIN $(APPVEYOR_REPO_TAG_NAME)'
    artifact: files
    draft: true
    prerelease: false
    force_update: true
    auth_token:
      secure: bKQ2RgyJSqBdrQV8TFJ/1oSxxUH2tEPbpiXiwDYI+Adf1rw3aqGBnUp6jtVmnsbbQuX5XvPIl23pXiWRuhxIm7PycgMKU0nHWg5DAt3ftGw71rLl5xv6mgLLoHU
    on:
      APPVEYOR_REPO_TAG: true       # deploy on tag push only

